### ISSUE TITLE
Some NTFS partition under GPT table not detected

### ISSUE THREAD

**Issue by Bob-YsPan** [undecidabot/ezntfs#1]
At my macOS 10.14, when I run the "diskutil list"
I can see the two types of NTFS partition...
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk2         128.0 GB   disk0s2
   3:       Microsoft Basic Data Win&Mac                 171.6 GB   disk0s3    >>    exFAT
   4:       Microsoft Basic Data Windows                 199.9 GB   disk0s4    >>    under GPT table, NTFS and exFAT partition shows "Microsoft Basic Data"

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *320.1 GB   disk1
   1:               Windows_NTFS Windows 10_old          142.4 GB   disk1s1
   2:               Windows_NTFS Windows 7               42.9 GB    disk1s3
   3:               Windows_NTFS App&Data2               134.7 GB   disk1s5    >>    Under MBR partition table, NTFS partition shows "Windows_NTFS"(Can detect)

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +128.0 GB   disk2
                                 Physical Store disk0s2
   1:                APFS Volume MacOS                   38.3 GB    disk2s1
   2:                APFS Volume Preboot                 48.2 MB    disk2s2
   3:                APFS Volume Recovery                507.4 MB   disk2s3
   4:                APFS Volume VM                      5.4 GB     disk2s4

/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *1.0 TB     disk3
   1:               Windows_NTFS BOB_DATA                1.0 TB     disk3s1

Maybe this situation, so when I use ezntfs all, can't remount some partition under GPT tables.
(Sorry for my bad English... Chinese is my main language, so I still work hard to learn English...)

**Comment by lezgomatt** [comment]
Hi Bob,

Could you run `diskutil info disk0s3` and `diskutil info disk0s4`, and tell me what it says under "Type (Bundle)" and "File System Personality"?

If those two give different results, then we should be able to fix this by accepting the "Microsoft Basic Data" type. I won't be able to test it out myself though, so I'll need your help for this. Thanks.

> (Sorry for my bad English... Chinese is my main language, so I still work hard to learn English...)

No worries. 你的英文比我的中文好 :smile:

**Comment by Bob-YsPan** [comment]
Some different when I run these two command you mentioned...
***
_diskutil info disk0s3_

   Device Identifier:         disk0s3
   Device Node:               /dev/disk0s3
   Whole:                     No
   Part of Whole:             disk0

   Volume Name:               Win&Mac
   Mounted:                   Yes
   Mount Point:               /Volumes/Win&Mac

   Partition Type:            Microsoft Basic Data
   **File System Personality:   ExFAT
   Type (Bundle):             exfat
   Name (User Visible):       ExFAT**

   OS Can Be Installed:       No
   Media Type:                Generic
   Protocol:                  SATA
   SMART Status:              Verified
   Volume UUID:               275BA069-029B-397D-810F-E8FCEE3E4876
   Disk / Partition UUID:     2D0566A2-3D64-47D7-AC5F-6AA979157EED
   Partition Offset:          128344653824 Bytes (250673152 512-Byte-Device-Blocks)

   Disk Size:                 171.6 GB (171628822528 Bytes) (exactly 335212544 512-Byte-Units)
   Device Block Size:         512 Bytes

   Volume Total Space:        171.6 GB (171622531072 Bytes) (exactly 335200256 512-Byte-Units)
   Volume Used Space:         19.4 GB (19400884224 Bytes) (exactly 37892352 512-Byte-Units) (11.3%)
   Volume Free Space:         152.2 GB (152221646848 Bytes) (exactly 297307904 512-Byte-Units) (88.7%)
   Allocation Block Size:     131072 Bytes

   Read-Only Media:           No
   Read-Only Volume:          No

   Device Location:           Internal
   Removable Media:           Fixed

   Solid State:               No
   Hardware AES Support:      No
***
_diskutil info disk0s4_

   Device Identifier:         disk0s4
   Device Node:               /dev/disk0s4
   Whole:                     No
   Part of Whole:             disk0

   Volume Name:               Windows
   Mounted:                   Yes
   Mount Point:               /Volumes/Windows

   Partition Type:            Microsoft Basic Data
   **File System Personality:   NTFS
   Type (Bundle):             ntfs
   Name (User Visible):       Windows NT File System (NTFS)**

   OS Can Be Installed:       No
   Media Type:                Generic
   Protocol:                  SATA
   SMART Status:              Verified
   Volume UUID:               A43C1CEA-5659-4C65-A97D-D03187568D23
   Disk / Partition UUID:     FDD88969-C2CF-483E-B36D-826ADD522C1E
   Partition Offset:          300108742656 Bytes (586149888 512-Byte-Device-Blocks)

   Disk Size:                 199.9 GB (199864877056 Bytes) (exactly 390361088 512-Byte-Units)
   Device Block Size:         512 Bytes

   Volume Total Space:        199.9 GB (199864872960 Bytes) (exactly 390361080 512-Byte-Units)
   Volume Used Space:         30.8 GB (30799396864 Bytes) (exactly 60155072 512-Byte-Units) (15.4%)
   Volume Free Space:         169.1 GB (169065476096 Bytes) (exactly 330206008 512-Byte-Units) (84.6%)
   Allocation Block Size:     4096 Bytes

   Read-Only Media:           No
   Read-Only Volume:          Yes

   Device Location:           Internal
   Removable Media:           Fixed

   Solid State:               No
   Hardware AES Support:      No

**Comment by lezgomatt** [comment]
I just pushed a fix for this and published it on PyPI (v0.1.3).

Please test it out and close this issue after confirming that it has been resolved. Thanks!

**Comment by Bob-YsPan** [comment]
Ok, It works!!!
Thank you very much.
