### ISSUE TITLE
error when "pip3 install ezntfs" and "sudo ezntfs-app install"

### ISSUE THREAD

**Issue by tonho911** [undecidabot/ezntfs#11]
I have 2 error when pip3 install ezntfs

 #   1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyobjc-core
  Running setup.py clean for pyobjc-core
  Building wheel for pyobjc-framework-Cocoa (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [524 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site

 #     1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyobjc-framework-Cocoa
  Running setup.py clean for pyobjc-framework-Cocoa
Failed to build pyobjc-core pyobjc-framework-Cocoa
ERROR: Could not build wheels for pyobjc-core, pyobjc-framework-Cocoa, which is required to install pyproject.toml-based projects

and 

when sudo ezntfs-app install
sudo: ezntfs-app: command not found

what I've done is change the python installer to the latest version and downgrade and the results are the same, what should I do bro?
I use Mac OS Sonoma 14.1.1

 Thank for your help sir

**Comment by lezgomatt** [comment]
Hey @tonho911, this error is due to an incompatibility between Python 3.12 and (the older version of) `pyobjc`. Unfortunately, the newer versions of `pyobjc` has a different bug (https://github.com/ronaldoussoren/pyobjc/issues/575), so we're stuck with the older version right now.

If you can downgrade to Python 3.11, then I believe it should work.

**Comment by tonho911** [comment]
bro @lezgomatt ....
yeah bro...
when I use Python version 3.11.7 it works normally and successfully installs ezntfs
thank you for your attention
