### ISSUE TITLE
Error during install in Monterey

### ISSUE THREAD

**Issue by startergo** [undecidabot/ezntfs#5]
```
sudo ezntfs-app install        
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/ezntfs-app", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ezntfs/app.py", line 339, in main
    return install()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ezntfs/app.py", line 405, in install
    with open(launchd_config_path, "w") as launchd_config_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mbp115/Library/LaunchAgents/com.lezgomatt.ezntfs.plist'
```

```
where python
python: aliased to python3
/opt/local/bin/python
/usr/local/bin/python
```

**Comment by lezgomatt** [comment]
Hi @startergo, does the directory `/Users/mbp115/Library/LaunchAgents` exist? If not, please create it and try again.

I'll automatically create this directory in the next release. Thanks! 😄

**Comment by startergo** [comment]
The directory:
```/Library/LaunchAgents``` exists.
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/7897244/153871590-f86f5fe2-d493-486d-b30f-a00eb5af1345.png">
I have created ```/Users/mbp115/Library/LaunchAgents``` and re-ran :
```
sudo ezntfs-app install
Installation complete! Try plugging an NTFS drive in.
NOTE: You may need to grant python access to removable volumes.
```

**Comment by lezgomatt** [comment]
> The directory: `/Library/LaunchAgents` exists.

Ah, this directory is similar but applied for all users.

> I have created `/Users/mbp115/Library/LaunchAgents` and re-ran :
> 
> ```
> sudo ezntfs-app install
> Installation complete! Try plugging an NTFS drive in.
> NOTE: You may need to grant python access to removable volumes.
> ```

Nice! I will work on the fix in a little bit. Thanks again for the bug report!
