### ISSUE TITLE
ERROR: Failed to detect macFUSE.

### ISSUE THREAD

**Issue by hoochanlon** [undecidabot/ezntfs#8]
<img width="682" alt="截屏2023-01-07 15 12 10" src="https://user-images.githubusercontent.com/35732922/211138797-8b3475e3-4c5c-4da1-a28c-9e8b887c5f13.png">

**Comment by lezgomatt** [comment]
You need to install macFUSE and NTFS-3G yourself to use this.

The installer for macFUSE can be found here: https://osxfuse.github.io

Installing NTFS-3G is a bit tricker, the easiest (but least secure) way would be to install it via brew: https://github.com/osxfuse/osxfuse/wiki/NTFS-3G#installation

A more secure way would be to install it via nix (`nix-env -iA nixpkgs.ntfs3g`) or to compile it yourself (source code here: https://github.com/tuxera/ntfs-3g/tree/2022.10.3).
