### ISSUE TITLE
我想设置U盘的图标，可以操作吗？

### ISSUE THREAD

**Issue by hoochanlon** [undecidabot/ezntfs#9]
更改ezntfs挂载的U盘图标

**Comment by hoochanlon** [comment]
macOS与Windows图标设置是独立的，只能在所在的对应系统显示，而且由于Mac平台下NTFS的特殊性，配置图标操作尤为有限。不能直接配置在`/Volumes/`根目录，图标配置不当会导致挂载功能紊乱。解决办法：再安装一个同类的NTFS for Mac，只要不卸载，挂载功能紊乱，就不出继续出现。还想成当初的样子，得重装系统了。


配置NTFS磁盘图标缺陷颇多，在 `/Library/Filesystems/`以包内容显示macfuse.fs，可替换对应图标。

![](https://fastly.jsdelivr.net/gh/hoochanlon/Free-NTFS-for-Mac/shashin/icon-re.png)

通过 `sudo ntfs-3g /dev/disk4s1 ~/Desktop/mnt` 挂载可出现效果，可这样挂载忽略显示了NTFS已有文件，再复制同名到U盘会报错。

**Comment by lezgomatt** [comment]
I have not tested this myself, but you might want to try the [`volicon`](https://github.com/osxfuse/osxfuse/wiki/Mount-options#volicon) option of macFUSE.

Something like `sudo ntfs-3g -o volicon=/Users/chanlonhoo/downloads/Volume.icns /dev/disk4s1 ~/Desktop/mnt` might work. You'll want to add a few additional options as well, see: https://github.com/lezgomatt/ezntfs/blob/b1413c8cf73ff269cd61c7477c5321a05f1383be/ezntfs/ezntfs.py#L138-L148

Hope that helps 😃
